import '../../../presentation/widgets/main/generic_tree_view/widget_tree_model_abs.dart';

class Customer extends IDataTreeModel {
  String address;
  int bankAccType;
  String bankCardNumber;
  int exchangeType;
  int cityId;
  int code;
  String nationalCode;
  String postalCode;
  String companyName;
  int sharePercentage;
  DateTime foundationDate;
  String description;
  int creditCheck;
  int creditRial;
  String fax;
  String firstName;
  int groupValueId;
  String responsibleBoard;
  bool isActive;
  bool isBlackList;
  bool isBoardMember;
  bool isStaff;
  bool isCustomer;
  bool isInvestee;
  bool isOther;
  bool isPartner;
  bool isSupply;
  bool isFacilitator;
  bool isReceiverFacility;
  bool isDependent;
  bool isIntermediary;
  int kind;
  String lastName;
  String name;
  int parentId;
  String passportNumber;
  int prefixId;
  String jobTitle;
  String ShebaNumber;
  String registrationNumber;
  String nationality;
  int detailId;
  String tel;
  int type;

  Customer(
      {required super.displayName,
      required super.id,
      required super.hasChildren,
      required super.children,
      required this.address,
      required this.bankAccType,
      required this.bankCardNumber,
      required this.exchangeType,
      required this.cityId,
      required this.code,
      required this.nationalCode,
      required this.postalCode,
      required this.companyName,
      required this.sharePercentage,
      required this.foundationDate,
      required this.description,
      required this.creditCheck,
      required this.creditRial,
      required this.fax,
      required this.firstName,
      required this.groupValueId,
      required this.responsibleBoard,
      required this.isActive,
      required this.isBlackList,
      required this.isBoardMember,
      required this.isStaff,
      required this.isCustomer,
      required this.isInvestee,
      required this.isOther,
      required this.isPartner,
      required this.isSupply,
      required this.isFacilitator,
      required this.isReceiverFacility,
      required this.isDependent,
      required this.isIntermediary,
      required this.kind,
      required this.lastName,
      required this.name,
      required this.parentId,
      required this.passportNumber,
      required this.prefixId,
      required this.jobTitle,
      required this.ShebaNumber,
      required this.registrationNumber,
      required this.nationality,
      required this.detailId,
      required this.tel,
      required this.type});
}
